window.MAISTER_DATA = {
  generated: "2026-07-15T20:39:03Z",
  task: {
    title: "Implement recruiter-scannable profile README redesign",
    type: "development",
    status: "completed",
    description: "Implement the approved product-design brief: replace profile/README.md content per the redesign in .maister/tasks/product-design/2026-07-15-recruiter-scannable-profile/",
    path: ".maister/tasks/development/2026-07-15-recruiter-scannable-profile",
    current_activity: null
  },
  characteristics: {
    has_reproducible_defect: false,
    modifies_existing_code: true,
    creates_new_entities: false,
    involves_data_operations: false,
    ui_heavy: false
  },
  phases: [
    { id: "phase-1", name: "Analyze codebase & clarify requirements", icon_hint: "analysis", status: "completed", started: "2026-07-15T18:52:15Z", completed: "2026-07-15T19:04:14Z", skip_reason: null, summary: "profile/README.md is a stale intermediate draft, not the approved final content. Full replacement needed using feature-spec.md. Low risk.", decisions: [{decision: "Proceed with implementation now; defer branch divergence sync", rationale: "Not blocking for content-only change"}, {decision: "Full overwrite of profile/README.md only", rationale: "Working tree materially differs from approved content"}], risks: ["Local draft and origin/draft have diverged over profile/README.md — will likely surface as a merge conflict later; deferred per user"], artifacts: [{path: "analysis/codebase-analysis.md", label: "Codebase analysis", html: null}, {path: "analysis/clarifications.md", label: "Clarifications", html: null}], gate: null },
    { id: "phase-2", name: "Analyze gaps & clarify scope", icon_hint: "analysis", status: "completed", started: "2026-07-15T19:04:14Z", completed: "2026-07-15T19:13:23Z", skip_reason: null, summary: "Single-file content overwrite, modificative change. Only modifies_existing_code=true. Risk/effort both low.", decisions: [{decision: "Verify reachable links during Phase 11, defer only GitHub-render check to post-merge", rationale: "Cheap to catch a bad link now"}], risks: ["Calendar link domain (cal.eu) unverified"], artifacts: [{path: "analysis/gap-analysis.md", label: "Gap analysis", html: null}, {path: "analysis/scope-clarifications.md", label: "Scope clarifications", html: null}], gate: {question: "Continue to Phase 5?", answer: "Yes, continue to Phase 5"} },
    { id: "phase-3", name: "Write failing test (TDD Red)", icon_hint: "code", status: "skipped", started: null, completed: "2026-07-15T19:13:23Z", skip_reason: "has_reproducible_defect=false — no bug to reproduce, this is a content replacement", summary: null, decisions: [], risks: [], artifacts: [], gate: null },
    { id: "phase-4", name: "Generate UI mockups", icon_hint: "plan", status: "skipped", started: null, completed: "2026-07-15T19:13:23Z", skip_reason: "ui_heavy=false — static Markdown content, no components/routes/nav; visual design already resolved and approved in the product-design workflow", summary: null, decisions: [], risks: [], artifacts: [], gate: null },
    { id: "phase-5", name: "Gather requirements & create specification", icon_hint: "spec", status: "in_progress", started: "2026-07-15T19:13:23Z", completed: "2026-07-15T19:24:42Z", skip_reason: null, summary: "Lean spec created: full verbatim overwrite of profile/README.md. 4 core requirements, 0 new/reusable components. Self-verification passed all 4 checks.", decisions: [{decision: "Full overwrite, not incremental diff", rationale: "Working-tree draft differs materially"}, {decision: "Source of truth is feature-spec.md lines 109-159", rationale: "Not the git index or working tree"}, {decision: "Stage only profile/README.md post-overwrite", rationale: "Index holds an unrelated stale version"}], risks: ["Calendar link (cal.eu) domain unverified — checked in Phase 11", "GitHub-render check deferred to post-merge"], artifacts: [{path: "implementation/spec.md", label: "Specification", html: "implementation/spec.html"}], gate: null },
    { id: "phase-6", name: "Audit specification", icon_hint: "spec", status: "in_progress", started: "2026-07-15T19:24:42Z", completed: "2026-07-15T19:42:52Z", skip_reason: null, summary: "Pass-with-concerns: 0 critical/high, 2 medium, 3 low. Content fidelity independently verified byte-for-byte (MD5 match). Medium issues: git-staging success criterion needs a qualifier; standards-doc staleness not flagged.", decisions: [], risks: ["M-1: 'only profile/README.md staged' criterion ignores pre-existing unrelated staged files", "M-2: spec overstates 'no conflicts' with profile standards docs — placeholder convention is deliberately being removed, not followed"], artifacts: [{path: "verification/spec-audit.md", label: "Specification audit", html: null}], gate: null },
    { id: "phase-7", name: "Plan implementation", icon_hint: "plan", status: "completed", started: "2026-07-15T19:42:52Z", completed: "2026-07-15T19:48:03Z", skip_reason: null, summary: "1 task group, 4 steps, 7 manual verification checks. No Testing Review group. Visual coverage: 1/1 screens covered.", decisions: [{decision: "Single task group, not split further", rationale: "One file overwrite; splitting adds no benefit"}, {decision: "'Define checklist' step replaces 'write tests' step", rationale: "No automated test suite exists"}], risks: ["M-1: step 1.4(c) checks the delta rather than literal staging count", "M-2: standards docs will have stale citations post-overwrite"], artifacts: [{path: "implementation/implementation-plan.md", label: "Implementation plan", html: "implementation/implementation-plan.html"}, {path: "implementation/visual-coverage.md", label: "Visual coverage matrix", html: null}], gate: {question: "Continue to implementation?", answer: "Yes, continue to Phase 8"} },
    { id: "phase-8", name: "Execute implementation", icon_hint: "code", status: "in_progress", started: "2026-07-15T19:48:49Z", completed: "2026-07-15T20:18:10Z", skip_reason: null, summary: "Group 1 executed successfully: profile/README.md overwritten (SHA-256 verified byte-identical to source). All 7 manual checks passed; 2 deferred checks logged. Visual compliance: zero deviations.", decisions: [], risks: ["GitHub-native rendering check remains deferred to post-merge"], artifacts: [{path: "implementation/work-log.md", label: "Work log", html: null}, {path: "profile/README.md", label: "Replaced profile README content", html: null}], gate: null },
    { id: "phase-9", name: "Verify test passes (TDD Green)", icon_hint: "verify", status: "skipped", started: null, completed: "2026-07-15T20:18:10Z", skip_reason: "Phase 3 (TDD Red) was not executed — no reproducible defect", summary: null, decisions: [], risks: [], artifacts: [], gate: null },
    { id: "phase-10", name: "Prompt verification options", icon_hint: "verify", status: "completed", started: "2026-07-15T20:18:10Z", completed: "2026-07-15T20:20:26Z", skip_reason: null, summary: "Code review, pragmatic review, reality check, production readiness all enabled. E2E and user docs skipped (not applicable to a static content page).", decisions: [], risks: [], artifacts: [], gate: {question: "Which verifications to run?", answer: "Code review, Pragmatic review, Reality check, Production readiness"} },
    { id: "phase-11", name: "Verify implementation & resolve issues", icon_hint: "verify", status: "completed", started: "2026-07-15T20:20:26Z", completed: "2026-07-15T20:37:47Z", skip_reason: null, summary: "Passed with Issues (post-fix). 0 critical defects in the implementation itself. 2 fixable warnings fixed and re-checked (LinkedIn URL, stale standards docs). 2 pre-existing repo-level risks remain (CV.md PII staged; draft/origin divergence) — neither introduced by this task.", decisions: [{decision: "Fix the 2 in-scope items, leave repo-level items residual", rationale: "Repo-level items require the user's own decision"}, {decision: "Skip full re-verification, direct manual re-check instead", rationale: "Fixes trivial and low-risk"}], risks: ["resolved: LinkedIn URL trailing-slash inconsistency", "resolved: stale standards-doc citations", "CV.md staged with unredacted PII in a public repo — needs your decision", "draft/origin-draft diverged over profile/README.md — already deferred"], artifacts: [{path: "verification/implementation-verification.md", label: "Implementation verification", html: "verification/implementation-verification.html"}, {path: "verification/code-review-report.md", label: "Code review", html: null}, {path: "verification/pragmatic-review.md", label: "Pragmatic review", html: null}, {path: "verification/production-readiness-report.md", label: "Production readiness", html: null}, {path: "verification/reality-check.md", label: "Reality check", html: null}], gate: {question: "Which issues to fix?", answer: "Fix the 2 in-scope items now"} },
    { id: "phase-12", name: "Run E2E tests", icon_hint: "verify", status: "skipped", started: null, completed: "2026-07-15T20:20:26Z", skip_reason: "e2e_enabled=false — static content page, not an interactive app", summary: null, decisions: [], risks: [], artifacts: [], gate: null },
    { id: "phase-13", name: "Generate user documentation", icon_hint: "docs", status: "skipped", started: null, completed: "2026-07-15T20:20:26Z", skip_reason: "user_docs_enabled=false — no new feature/workflow for end-users", summary: null, decisions: [], risks: [], artifacts: [], gate: null },
    { id: "phase-14", name: "Finalize workflow", icon_hint: "done", status: "completed", started: "2026-07-15T20:37:47Z", completed: "2026-07-15T20:39:03Z", skip_reason: null, summary: "Workflow complete. profile/README.md fully replaced with the approved recruiter-scannable redesign. 2 residual repo-level risks flagged for operator follow-up (CV.md PII, branch divergence).", decisions: [], risks: [], artifacts: [], gate: {question: "Continue to finalization?", answer: "Yes, finalize"} }
  ],
  verification: { status: null, issues: [], fixes: [], reverify_count: 0 }
};
