window.MAISTER_DATA = {
  generated: "2026-07-15T18:49:55Z",
  task: {
    title: "Recruiter-scannable profile README redesign",
    type: "product-design",
    status: "completed",
    description: "Update profile/README.md as a business card for a recruiter scanning in 15 seconds",
    path: ".maister/tasks/product-design/2026-07-15-recruiter-scannable-profile",
    current_activity: null
  },
  characteristics: {
    is_greenfield: false,
    is_enhancement: true,
    is_ui_focused: true,
    is_backend: false,
    is_complex: false,
    is_simple: true
  },
  phases: [
    { id: "phase-0", name: "Initialize, gather context & detect characteristics", icon_hint: "analysis", status: "completed", started: "2026-07-15T12:17:50Z", completed: "2026-07-15T13:25:33Z", skip_reason: null, summary: "Characteristics confirmed: enhancement + UI-focused + simple. User supplied CV.md and assumptions.md (own design brief).", decisions: [{decision: "Characteristics confirmed as enhancement + is_ui_focused + is_simple", rationale: "Single existing page, content/visual scannability focus, well-defined scope"}], risks: [], artifacts: [{path: "context/CV.md", label: "Full CV (user-supplied)", html: null}, {path: "context/assumptions.md", label: "User's own design brief (Polish)", html: null}], gate: {question: "Characteristics confirmed?", answer: "Correct, proceed with these"} },
    { id: "phase-1", name: "Synthesize all context sources", icon_hint: "analysis", status: "completed", started: "2026-07-15T13:25:33Z", completed: "2026-07-15T13:36:22Z", skip_reason: null, summary: "Synthesized project docs, codebase-analysis.md, CV.md, and assumptions.md. Recovered real skill-flip content (live demo + tech stack), resolving the placeholder. One real open design choice remains: intro framing.", decisions: [], risks: ["CV framing is notably more senior than the README's current wording — needs a Phase 2 decision.", "CV lists a meetings-calendar link not currently on the profile page — confirm whether to include."], artifacts: [{path: "analysis/codebase-analysis.md", label: "Codebase/content analysis", html: null}, {path: "analysis/design-context.md", label: "Unified design context synthesis", html: null}], gate: {question: "Context synthesis complete — any corrections before exploring the problem space?", answer: "Looks right, continue"} },
    { id: "phase-2", name: "Explore problem space", icon_hint: "analysis", status: "completed", started: "2026-07-15T13:36:22Z", completed: "2026-07-15T13:47:00Z", skip_reason: null, summary: "Problem statement, constraints, success criteria approved. Seniority framing resolved, calendar link added, intro kept descriptive.", decisions: [{decision: "Lead with CV-aligned seniority framing", rationale: "Matches actual CV positioning"}, {decision: "Add meetings-calendar link (cal.eu/bartek/meeting)", rationale: "Low-friction booking path"}, {decision: "Keep intro purely descriptive", rationale: "Avoids reading as less senior or dating quickly"}], risks: ["Whether to keep duplicate top/bottom contact blocks and the standalone Tech stack section is still open — deferred to Phase 4/5"], artifacts: [{path: "analysis/problem-statement.md", label: "Problem statement, constraints, success criteria", html: null}], gate: {question: "Problem statement approved?", answer: "Approve and continue"} },
    { id: "phase-3", name: "Explore users & personas", icon_hint: "analysis", status: "skipped", started: null, completed: "2026-07-15T13:47:00Z", skip_reason: "Not greenfield/complex (is_simple + is_enhancement) — personas not needed for a single-page recruiter-facing content redesign.", summary: null, decisions: [], risks: [], artifacts: [], gate: null },
    { id: "phase-4", name: "Generate design alternatives", icon_hint: "plan", status: "completed", started: "2026-07-15T13:47:00Z", completed: "2026-07-15T13:58:11Z", skip_reason: null, summary: "16 alternatives generated across 4 decision areas (contact placement, tech-stack section, About-org replacement, project order/density) with a recommended combination, medium-high confidence.", decisions: [], risks: ["The four decision areas are not fully independent — cutting 'About this org' entirely would remove the only page-level home for the honesty framing other alternatives assume exists."], artifacts: [{path: "analysis/alternatives.md", label: "Design alternatives", html: "analysis/alternatives.html"}], gate: null },
    { id: "phase-5", name: "Converge on design direction", icon_hint: "plan", status: "completed", started: "2026-07-15T13:58:11Z", completed: "2026-07-15T14:05:13Z", skip_reason: null, summary: "All 4 decision areas resolved to the recommended combination (1A, 2B, 3B, 4B).", decisions: [{decision: "Contact placement: Alternative 1A", rationale: "Matches user's own assumptions.md brief"}, {decision: "Tech-stack section: Alternative 2B", rationale: "Fixes accuracy problem, adds breadth signal"}, {decision: "About-org: Alternative 3B", rationale: "Near-direct match to user's brief"}, {decision: "Project order/density: Alternative 4B", rationale: "Resolves scan-speed without framing mismatch"}], risks: ["3B/4B execution quality moves to Phase 6", "2B repositioning is a real structural change — quick visual check recommended after implementation"], artifacts: [{path: "analysis/design-decisions.md", label: "Selected approach, rationale, trade-offs", html: "analysis/design-decisions.html"}], gate: {question: "Design direction approved — continue to Feature Specification?", answer: "Yes, continue"} },
    { id: "phase-6", name: "Specify features section-by-section", icon_hint: "spec", status: "completed", started: "2026-07-15T14:05:13Z", completed: "2026-07-15T17:44:16Z", skip_reason: null, summary: "4 sections drafted and approved: intro/contact, tech-stack signal, hook+projects, closing contact. Full assembled page written. 5/6 success criteria met.", decisions: [], risks: ["resolved: page renders cleanly — verified via Phase 7 mockup"], artifacts: [{path: "analysis/feature-spec.md", label: "Full section-by-section spec + assembled page", html: "analysis/feature-spec.html"}], gate: {question: "Specification complete — continue to Visual Prototyping?", answer: "Yes, continue"} },
    { id: "phase-7", name: "Create visual prototypes", icon_hint: "code", status: "in_progress", started: "2026-07-15T17:44:16Z", completed: "2026-07-15T18:29:33Z", skip_reason: null, summary: "Rendered a mid-fidelity mockup mimicking GitHub's markdown rendering with live shields.io badges and annotations for each design decision. Approved on first review.", decisions: [], risks: [], artifacts: [{path: "analysis/mockups/aib-org-profile-full-page-rendered-preview.html", label: "Rendered page mockup", html: "analysis/mockups/aib-org-profile-full-page-rendered-preview.html"}], gate: {question: "Mockup review — how does it look?", answer: "Approve all screens and continue"} },
    { id: "phase-8", name: "Review & hand off product brief", icon_hint: "done", status: "completed", started: "2026-07-15T18:29:33Z", completed: "2026-07-15T18:49:55Z", skip_reason: null, summary: "Layered product brief assembled from all phase artifacts and approved on first review. Visual companion server shut down. Workflow complete.", decisions: [], risks: [], artifacts: [{path: "outputs/product-brief.md", label: "Final product brief", html: "outputs/product-brief.html"}], gate: {question: "Product brief approved?", answer: "Approve product brief"} }
  ],
  verification: { status: null, issues: [], fixes: [], reverify_count: 0 }
};
